# Generated by Django 4.0.4 on 2022-06-15 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0004_category_name_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='DEFAULT VALUE', max_length=200),
        ),
    ]
